### ISSUE TITLE
-size_required_What is the quantity unit

### ISSUE THREAD

**Issue by Tianyou96** [linzhi2013/extractfq#1]
I want to get 5GB files
![图片](https://user-images.githubusercontent.com/51896128/74899525-2068c580-53d8-11ea-874c-3dc1bac3b96b.png)
![图片](https://user-images.githubusercontent.com/51896128/74899526-21015c00-53d8-11ea-9279-2edfed367d1a.png)
size_required 5
but I got only 1GB in this setting
size_required_What is the quantity unit？

**Comment by linzhi2013** [comment]
Hi zskysafe,

that's weird. In the extractfq, the input number will be changed to `size_required = size_required * (10**9)`, i.e., the assumed quantity unit is Gigabase.

How many bases do your input files (`*.clean.fq.gz`) have? Could it be your input file have only 1 GB data?

**Comment by Tianyou96** [comment]
![图片](https://user-images.githubusercontent.com/51896128/74903582-501dca80-53e4-11ea-82b5-c45a23bd6be8.png)
I understand it should be the result of gz

**Comment by linzhi2013** [comment]
Looks your fq file is normal.

How did you install the `extractfq`? with `conda` ? I want to check that then.

**Comment by Tianyou96** [comment]
/ apps/anaconda3/bin/extractfq -fq1 $fq1 -fq2 $fq2 -outfq1 $outfq1 -outfq2 $outfq2 -gz -size_ required 5
I chose -gz ，It should be because gz compressed the size
Does a 6GB file mean there is 6Gigabase？
I originally thought that it should be a 5Gigabyte（size） file after execution

**Comment by linzhi2013** [comment]
'Does a 6GB file mean there is 6Gigabase？'
> No, a 6GB file (uncompressed) is about 2 Gbp (or 1Gbp) data. Because A fastQ file consist of 4 lines.

Can you tell me what did you mean you only got 1GB?  does the size of the file? One cannot determine the total base pairs from a compressed file.

**Comment by Tianyou96** [comment]
Thank you very much for explaining these
 I understand something wrong. I'm not used to describing size in base pairs
So I thought size_required was Gigabyte.
I know size_required is Gigabase now, thanks for your help

**Comment by linzhi2013** [comment]
You're welcome. I'm glad you figured it out.
